#!/usr/bin/env bash
#
#  install-ncursesw
#
#  Copyright (c) 2018 Stephen Whittle  All rights reserved.
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"),
#  to deal in the Software without restriction, including without limitation
#  the rights to use, copy, modify, merge, publish, distribute, sublicense,
#  and/or sell copies of the Software, and to permit persons to whom
#  the Software is furnished to do so, subject to the following conditions:
#  The above copyright notice and this permission notice shall be included
#  in all copies or substantial portions of the Software.
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
#  IN THE SOFTWARE.

if [[ $(id -u) -ne 0 ]] ; then
    printf "must be a superuser!!!\n" >&2

    exit 1
fi

package="ncurses"

install_dir="/usr/local/src/$package"
archive_version="6.0"
archive_file="$package-$archive_version.tar.gz"

apt-get update
rc=$?

[[ $rc -ne 0 ]] && exit $rc

apt-get -y install wget \
                   pkg-config \
                   grep \
                   build-essential
rc=$?

[[ $rc -ne 0 ]] && exit $rc

if [[ ! -d "$install_dir" ]] ; then
    mkdir --parents \
          "$install_dir"
    rc=$?

    [[ $rc -ne 0 ]] && exit $rc
fi

cd "$install_dir"
rc=$?

[[ $rc -ne 0 ]] && exit $rc

if [[ ! -f "$archive_file" ]] ; then
    wget "ftp://ftp.invisible-island.net/$package/$archive_file"
    rc=$?

    [[ $rc -ne 0 ]] && exit $rc
fi

if [[ ! -d "$package-$archive_version" ]] ; then
    tar -zxvf "$archive_file"
    rc=$?

    [[ $rc -ne 0 ]] && exit $rc
fi

cd "$package-$archive_version"
rc=$?

[[ $rc -ne 0 ]] && exit $rc

./configure --prefix=/usr \
            --enable-pc-files \
            --with-shared \
            --enable-widec \
            --enable-ext-colors \
            --enable-ext-mouse \
            --enable-ext-putwin \
            CPPFLAGS="-P"
rc=$?

[[ $rc -ne 0 ]] && exit $rc

make
rc=$?

[[ $rc -ne 0 ]] && exit $rc

make install
rc=$?

[[ $rc -ne 0 ]] && exit $rc

ldconfig
rc=$?

[[ $rc -ne 0 ]] && exit $rc

package="${package}w"

prefix="$(pkg-config --variable=prefix \
                     "$package")"

pc_file="$(find "$prefix" \
                -name "$package.pc" \
                -print | \
           grep --invert-match \
                "/usr/local/src" | \
           head --lines=1)"

if [[ -f "$pc_file" ]] ; then
    pc_dir="$(dirname "$pc_file")"

    swift_pc_file="$pc_dir/${package}-swift.pc"

    awk -F: '{
        if ($1 == "Description") {
            printf("%s add-on for CNCursesw swift module\n", $0)
        } else if ($1 == "Libs") {
            printf("%s%s -lpanelw %s\n", $1, FS, $2)
        } else if ($1 == "Cflags") {
            printf("%s%s\n", $1, FS)
        } else {
            printf("%s\n", $0)
        }
    }' "$pc_file" 1>"$swift_pc_file" \
                  2>/dev/null
    rc=$?

    [[ $rc -ne 0 ]] && exit $rc
fi

exit 0
